### ISSUE TITLE
can you help me to setup chat files on live website how to make locahost to live url

### ISSUE THREAD

**Issue by gagandeepLamba** [jewirth/TCPchat#1]
can you help me to setup chat files on live website how to make locahost to live url gaganlamba.site88.net

**Comment by jewirth** [comment]
I just created a new repository called [WebChat](https://github.com/jewirth/WebChat). I think that is exactly what you are looking for? Of course, you need to deploy the app on your server. However, it should run fine locally on any system for testing.

PS. I put it online for testing [here](http://hys.snej.de:3001/). No guarantee about how long I keep it online!

**Comment by gagandeepLamba** [comment]
sir thanks for this help can you please tell me how to deploy on server??

**Comment by jewirth** [comment]
I would recommend to first try to run the chat-server locally on your computer using a local installation of node.js which you can get at http://nodejs.org

Then, if you feel comfortable with it, deploy it online using this documentation:
https://devcenter.heroku.com/articles/getting-started-with-nodejs#introduction
